web:
  build: .
  dockerfile: Dockerfile-development
  ports:
   - "8000:8000"
  volumes:
   - .:/usr/src/app/
   - /usr/src/app/node_modules
   - /usr/src/app/dist
  environment:
   NODE_ENV: development
